# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QPixmap
import modelcv as cv
import mysql.connector


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # Đọc file labels
        class_names_list = open(
            "test\labels.txt", "r").readlines()
        # Lấy từng tên đối tượng trong file label bỏ vào một list để bỏ vào combobox
        for i in range(len(class_names_list)):
            name = class_names_list[i]
            name = name[2:]
            name = name.strip()
            class_names_list[i] = name
        # Khởi tạo các đối tượng trên giao diện
        Dialog.setObjectName("Dialog")
        Dialog.resize(788, 585)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(100, 0, 571, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.sideFrm = QtWidgets.QWidget(parent=Dialog)
        self.sideFrm.setGeometry(QtCore.QRect(0, 110, 121, 431))
        self.sideFrm.setStyleSheet(
            "background-color:  qlineargradient( x1:0 y1:0, x2:1 y2:0, stop:0 cyan, stop:1 blue)")
        self.sideFrm.setObjectName("sideFrm")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sideFrm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tiepNhanBtn = QtWidgets.QPushButton(parent=self.sideFrm)
        self.tiepNhanBtn.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.tiepNhanBtn.setStyleSheet("font: 8pt \"Arial\";")
        self.tiepNhanBtn.setFlat(False)
        self.tiepNhanBtn.setObjectName("tiepNhanBtn")
        self.verticalLayout.addWidget(self.tiepNhanBtn)
        self.tcBtn = QtWidgets.QPushButton(parent=self.sideFrm)
        self.tcBtn.setCursor(QtGui.QCursor(
            QtCore.Qt.CursorShape.PointingHandCursor))
        self.tcBtn.setStyleSheet("font: 8pt \"Arial\";")
        self.tcBtn.setFlat(False)
        self.tcBtn.setObjectName("tcBtn")
        self.verticalLayout.addWidget(self.tcBtn)
        self.khBtn = QtWidgets.QPushButton(parent=self.sideFrm)
        self.khBtn.setStyleSheet("font: 8pt \"Arial\";")
        self.khBtn.setFlat(False)
        self.khBtn.setObjectName("khBtn")
        self.verticalLayout.addWidget(self.khBtn)
        self.h = QtWidgets.QPushButton(parent=self.sideFrm)
        self.h.setStyleSheet("font: 8pt \"Arial\";")
        self.h.setAutoDefault(True)
        self.h.setFlat(False)
        self.h.setObjectName("h")
        self.verticalLayout.addWidget(self.h)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, -1, 121, 111))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Dialog)
        self.stackedWidget.setGeometry(QtCore.QRect(130, 110, 651, 371))
        self.stackedWidget.setObjectName("stackedWidget")
        self.tiepNhanPage = QtWidgets.QWidget()
        self.tiepNhanPage.setObjectName("tiepNhanPage")
        self.label_2 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_2.setGeometry(QtCore.QRect(9, 9, 32, 16))
        self.label_2.setObjectName("label_2")
        self.cccdTxt = QtWidgets.QLineEdit(parent=self.tiepNhanPage)
        self.cccdTxt.setGeometry(QtCore.QRect(91, 9, 181, 18))
        self.cccdTxt.setObjectName("cccdTxt")
        self.sdtTxt = QtWidgets.QLineEdit(parent=self.tiepNhanPage)
        self.sdtTxt.setGeometry(QtCore.QRect(91, 33, 181, 19))
        self.sdtTxt.setObjectName("sdtTxt")
        self.label_3 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_3.setGeometry(QtCore.QRect(9, 33, 66, 16))
        self.label_3.setObjectName("label_3")
        self.hoTenTxt = QtWidgets.QLineEdit(parent=self.tiepNhanPage)
        self.hoTenTxt.setGeometry(QtCore.QRect(91, 58, 181, 18))
        self.hoTenTxt.setObjectName("hoTenTxt")
        self.label_4 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_4.setGeometry(QtCore.QRect(9, 58, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_5.setGeometry(QtCore.QRect(9, 82, 28, 16))
        self.label_5.setObjectName("label_5")
        self.emailTxt = QtWidgets.QLineEdit(parent=self.tiepNhanPage)
        self.emailTxt.setGeometry(QtCore.QRect(91, 82, 181, 19))
        self.emailTxt.setObjectName("emailTxt")
        self.label_6 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_6.setGeometry(QtCore.QRect(10, 140, 71, 16))
        self.label_6.setObjectName("label_6")
        self.dvCB = QtWidgets.QComboBox(parent=self.tiepNhanPage)
        self.dvCB.setGeometry(QtCore.QRect(90, 140, 131, 22))
        self.dvCB.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.dvCB.setEditable(False)
        self.dvCB.setObjectName("dvCB")
        self.dvCB.addItem("")
        self.dvCB.addItem("")
        self.dvCB.addItem("")
        self.dvCB.addItem("")
        self.tn_camBtn = QtWidgets.QPushButton(parent=self.tiepNhanPage)
        self.tn_camBtn.setGeometry(QtCore.QRect(340, 140, 75, 23))
        self.tn_camBtn.setObjectName("tn_camBtn")

        # Sự kiện nút mở camera và chụp hình ở trang chính
        self.tn_camBtn.clicked.connect(lambda: settcImg())
        self.tn_addBtn = QtWidgets.QPushButton(parent=self.tiepNhanPage)
        self.tn_addBtn.setGeometry(QtCore.QRect(250, 140, 75, 23))
        self.tn_addBtn.setObjectName("tn_addBtn")
        self.camFram = QtWidgets.QFrame(parent=self.tiepNhanPage)
        self.camFram.setGeometry(QtCore.QRect(430, 10, 221, 171))
        self.camFram.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.camFram.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.camFram.setObjectName("camFram")
        self.label_12 = QtWidgets.QLabel(parent=self.camFram)
        self.label_12.setGeometry(QtCore.QRect(0, 0, 221, 171))
        self.label_12.setText("")
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.loaiThuCB = QtWidgets.QComboBox(parent=self.tiepNhanPage)
        self.loaiThuCB.setGeometry(QtCore.QRect(90, 110, 131, 22))
        self.loaiThuCB.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight)
        self.loaiThuCB.setEditable(False)
        self.loaiThuCB.setCurrentText("")
        self.loaiThuCB.setObjectName("loaiThuCB")
        # Thêm các lựa chọn vào combobox
        self.loaiThuCB.addItems(class_names_list)

        # Bật camera ở trang chính
        def settcImg():
            img_name = cv.initCam()
            # Lấy giá trị tên hình
            pixmap = QPixmap(img_name[0])
            # Hiển thị hình sau khi chụp
            self.label_12.setPixmap(pixmap)
            # Đổi giá trị trong combobox với giá trị nhận dạng được
            self.loaiThuCB.setCurrentText(img_name[1])
            return img_name

        # Tạo trang Thú cưng
        self.label_7 = QtWidgets.QLabel(parent=self.tiepNhanPage)
        self.label_7.setGeometry(QtCore.QRect(10, 110, 81, 16))
        self.label_7.setObjectName("label_7")
        self.tableWidget_2 = QtWidgets.QTableWidget(parent=self.tiepNhanPage)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 191, 431, 171))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.stackedWidget.addWidget(self.tiepNhanPage)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.tcTable = QtWidgets.QTableWidget(parent=self.page)
        self.tcTable.setGeometry(QtCore.QRect(10, 170, 621, 192))
        self.tcTable.setObjectName("tcTable")
        self.tcTable.setColumnCount(0)
        self.tcTable.setRowCount(0)
        self.frame_2 = QtWidgets.QFrame(parent=self.page)
        self.frame_2.setGeometry(QtCore.QRect(380, 0, 141, 171))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        # Sự kiện cho các nút ở trang Thú cưng
        # Nút bật camera
        self.tc_camBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.tc_camBtn.setObjectName("tc_camBtn")
        self.tc_camBtn.clicked.connect(lambda: tc_settcImg())

        # Hàm xử lý bật camera, tương tự ở trang chính
        def tc_settcImg():
            img_name = cv.initCam()
            pixmap = QPixmap(img_name[0])
            self.label_13.setPixmap(pixmap)
            self.tc_loaiThuCB.setCurrentText(img_name[1])

        # Tạo trang Khách hàng
        self.gridLayout.addWidget(self.tc_camBtn, 0, 0, 1, 1)
        self.tc_confirmBtn = QtWidgets.QPushButton(parent=self.frame_2)
        self.tc_confirmBtn.setObjectName("tc_confirmBtn")
        self.gridLayout.addWidget(self.tc_confirmBtn, 1, 0, 1, 1)
        self.tc_camFrm = QtWidgets.QFrame(parent=self.page)
        self.tc_camFrm.setGeometry(QtCore.QRect(100, 0, 201, 171))
        self.tc_camFrm.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.tc_camFrm.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.tc_camFrm.setObjectName("tc_camFrm")
        self.tc_loaiThuCB = QtWidgets.QComboBox(parent=self.frame_2)
        self.gridLayout.addWidget(self.tc_loaiThuCB, 2, 0, 1, 1)
        self.tc_loaiThuCB.setGeometry(QtCore.QRect(90, 110, 131, 22))
        self.tc_loaiThuCB.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight)
        self.tc_loaiThuCB.setEditable(False)
        self.tc_loaiThuCB.setCurrentText("")
        self.tc_loaiThuCB.setObjectName("tc_loaiThuCB")
        self.tc_loaiThuCB.addItems(class_names_list)
        self.label_13 = QtWidgets.QLabel(parent=self.tc_camFrm)
        self.label_13.setGeometry(QtCore.QRect(0, 0, 201, 171))
        self.label_13.setText("")
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("tc_imLabel")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_8 = QtWidgets.QLabel(parent=self.page_2)
        self.label_8.setGeometry(QtCore.QRect(28, 31, 66, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.page_2)
        self.label_9.setGeometry(QtCore.QRect(28, 7, 32, 16))
        self.label_9.setObjectName("label_9")
        self.sdtTxt_kh = QtWidgets.QLineEdit(parent=self.page_2)
        self.sdtTxt_kh.setGeometry(QtCore.QRect(110, 31, 181, 19))
        self.sdtTxt_kh.setObjectName("sdtTxt_kh")
        self.emailTxt_kh = QtWidgets.QLineEdit(parent=self.page_2)
        self.emailTxt_kh.setGeometry(QtCore.QRect(110, 80, 181, 19))
        self.emailTxt_kh.setObjectName("emailTxt_kh")
        self.cccdTxt_kh = QtWidgets.QLineEdit(parent=self.page_2)
        self.cccdTxt_kh.setGeometry(QtCore.QRect(110, 7, 181, 18))
        self.cccdTxt_kh.setObjectName("cccdTxt_kh")
        self.hoTenTxt_kh = QtWidgets.QLineEdit(parent=self.page_2)
        self.hoTenTxt_kh.setGeometry(QtCore.QRect(110, 56, 181, 18))
        self.hoTenTxt_kh.setObjectName("hoTenTxt_kh")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(28, 56, 61, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.page_2)
        self.label_11.setGeometry(QtCore.QRect(28, 80, 28, 16))
        self.label_11.setObjectName("label_11")
        self.khTable = QtWidgets.QTableWidget(parent=self.page_2)
        self.khTable.setGeometry(QtCore.QRect(20, 160, 611, 192))
        self.khTable.setObjectName("khTable")
        self.khTable.setColumnCount(0)
        self.khTable.setRowCount(0)
        self.kh_updateBtn = QtWidgets.QPushButton(parent=self.page_2)
        self.kh_updateBtn.setGeometry(QtCore.QRect(110, 110, 181, 23))
        self.kh_updateBtn.setObjectName("kh_updateBtn")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.hd_ttBtn = QtWidgets.QPushButton(parent=self.page_3)
        self.hd_ttBtn.setGeometry(QtCore.QRect(50, 100, 75, 23))
        self.hd_ttBtn.setObjectName("hd_ttBtn")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(20, 170, 601, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.cccdTxt_kh_2 = QtWidgets.QLineEdit(parent=self.page_3)
        self.cccdTxt_kh_2.setGeometry(QtCore.QRect(692, 40, 181, 18))
        self.cccdTxt_kh_2.setObjectName("cccdTxt_kh_2")
        self.sdtTxt_kh_2 = QtWidgets.QLineEdit(parent=self.page_3)
        self.sdtTxt_kh_2.setGeometry(QtCore.QRect(692, 64, 181, 19))
        self.sdtTxt_kh_2.setObjectName("sdtTxt_kh_2")
        self.hoTenTxt_kh_2 = QtWidgets.QLineEdit(parent=self.page_3)
        self.hoTenTxt_kh_2.setGeometry(QtCore.QRect(692, 89, 181, 18))
        self.hoTenTxt_kh_2.setObjectName("hoTenTxt_kh_2")
        self.emailTxt_kh_2 = QtWidgets.QLineEdit(parent=self.page_3)
        self.emailTxt_kh_2.setGeometry(QtCore.QRect(692, 113, 181, 19))
        self.emailTxt_kh_2.setObjectName("emailTxt_kh_2")
        self.label_16 = QtWidgets.QLabel(parent=self.page_3)
        self.label_16.setGeometry(QtCore.QRect(60, 66, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.page_3)
        self.label_17.setGeometry(QtCore.QRect(60, 41, 66, 16))
        self.label_17.setObjectName("label_17")
        self.hd_makhTxt = QtWidgets.QLineEdit(parent=self.page_3)
        self.hd_makhTxt.setGeometry(QtCore.QRect(142, 17, 51, 18))
        self.hd_makhTxt.setObjectName("hd_makhTxt")
        self.label_18 = QtWidgets.QLabel(parent=self.page_3)
        self.label_18.setGeometry(QtCore.QRect(60, 17, 81, 16))
        self.label_18.setObjectName("label_18")
        self.hd_matcTxt = QtWidgets.QLineEdit(parent=self.page_3)
        self.hd_matcTxt.setGeometry(QtCore.QRect(142, 41, 51, 19))
        self.hd_matcTxt.setObjectName("hd_matcTxt")
        self.hd_ttTxt = QtWidgets.QLineEdit(parent=self.page_3)
        self.hd_ttTxt.setGeometry(QtCore.QRect(142, 66, 91, 18))
        self.hd_ttTxt.setObjectName("hd_ttTxt")
        self.label_19 = QtWidgets.QLabel(parent=self.page_3)
        self.label_19.setGeometry(QtCore.QRect(260, 70, 61, 16))
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.page_3)
        self.retranslateUi(Dialog)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # chụp hình rồi lưu vào thư mục folder, up lên giao diện
    # initCam() return 2 giá trị: 0 = tên file ảnh, 1 = tên động vật được nhận dạng

    # Kết nối cơ sở dữ liệu MySQL
    def load_to_table(self, table, tableWidget):
        self.mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="QuanLyThuY"
        )
        # Gán biến con trỏ để lấy dữ liệu các dòng
        self.mycursor = self.mydb.cursor()
        # Tạo các tiêu đề cột tùy theo các trang trên giao diện, kiểm tra tham số 'table'
        tables = {
            "ThuCung": ["idTC", "cccdKH", "loai", "dichvu", "urlhinh"],
            "KhachHang": ["cccd", "sdt", "hoten", "email"],
            "HoaDon": ["cccdKH", "idTC", "thanhTien"]
        }

        # Thực thi câu lệnh để con trỏ lấy tất cả các dòng từ database với tham số 'table' truyền vào
        self.mycursor.execute("SELECT * FROM " + str(table))

        # Lấy hết dữ liệu trong con trỏ
        result = self.mycursor.fetchall()

        # Lấy số dòng và số cột
        num_rows = len(result)
        num_cols = len(result[0])

        # Gán số dòng cột đó cho bảng cần hiển thị
        tableWidget.setRowCount(num_rows)
        tableWidget.setColumnCount(num_cols)

        # Đặt các tiêu đề cột cho bảng
        headers = tables[table]
        tableWidget.setHorizontalHeaderLabels(headers)

        # Lặp để đưa dữ liệu vào trong bảng
        for i, row in enumerate(result):
            for j, col in enumerate(row):
                item = QtWidgets.QTableWidgetItem(str(col))
                tableWidget.setItem(i, j, item)

    # Hàm xử lý khi chuyển đổi các trang trên giao diện
    def retranslateUi(self, Dialog):
        self.load_to_table("ThuCung", self.tableWidget_2)
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate(
            "Dialog", "<html><head/><body><p align=\"center\">Ứng dụng quản lý <br/>thú y</p></body></html>"))
        self.tiepNhanBtn.setText(_translate("Dialog", "Tiếp nhận thú cưng"))
        self.tiepNhanBtn.clicked.connect(
            lambda: self.stackedWidget.setCurrentIndex(0))
        self.tcBtn.setText(_translate("Dialog", "Thú cưng"))
        self.tcBtn.clicked.connect(
            lambda: self.stackedWidget.setCurrentIndex(1))
        self.khBtn.setText(_translate("Dialog", "Khách hàng"))
        self.khBtn.clicked.connect(
            lambda: self.stackedWidget.setCurrentIndex(2))
        self.h.setText(_translate("Dialog", "Hóa đon"))
        self.h.clicked.connect(lambda: self.stackedWidget.setCurrentIndex(3))
        self.stackedWidget.setStyleSheet(
            _translate("Dialog", "font: 8pt \"Arial\";"))
        self.label_2.setText(_translate("Dialog", "CCCD:"))
        self.label_3.setText(_translate("Dialog", "Số điện thoại:"))
        self.label_4.setText(_translate("Dialog", "Họ tên:"))
        self.label_5.setText(_translate("Dialog", "Email:"))
        self.label_6.setText(_translate("Dialog", "Loại dịch vụ:"))
        self.dvCB.setCurrentText(_translate("Dialog", "Trông giữ thú cưng"))
        self.dvCB.setItemText(0, _translate("Dialog", "Trông giữ thú cưng"))
        self.dvCB.setItemText(1, _translate("Dialog", "Khám định kỳ"))
        self.dvCB.setItemText(2, _translate("Dialog", "Chải lông"))
        self.dvCB.setItemText(3, _translate("Dialog", "Chích ngừa"))
        self.tn_camBtn.setText(_translate("Dialog", "Chụp hình"))
        self.tn_addBtn.setText(_translate("Dialog", "Xác nhận"))
        self.label_7.setText(_translate("Dialog", "Loài thú cưng"))
        self.tc_camBtn.setText(_translate("Dialog", "Chụp hình"))
        self.tc_confirmBtn.setText(_translate("Dialog", "Xác nhận sửa"))
        self.label_8.setText(_translate("Dialog", "Số điện thoại:"))
        self.label_9.setText(_translate("Dialog", "CCCD:"))
        self.label_10.setText(_translate("Dialog", "Họ tên:"))
        self.label_11.setText(_translate("Dialog", "Email:"))
        self.kh_updateBtn.setText(_translate("Dialog", "Cập nhật thông tin"))
        self.hd_ttBtn.setText(_translate("Dialog", "Thanh toán"))
        self.label_16.setText(_translate("Dialog", "Tổng tiền:"))
        self.label_17.setText(_translate("Dialog", "Mã thú cưng:"))
        self.label_18.setText(_translate("Dialog", "Mã khách hàng:"))
        self.label_19.setText(_translate("Dialog", "VND"))
        # Các sự kiện cho nút ở trang chính
        self.tn_addBtn.clicked.connect(self.add_both_to_database)
        self.tcBtn.clicked.connect(
            lambda: self.load_to_table("ThuCung", self.tcTable))
        self.khBtn.clicked.connect(
            lambda: self.load_to_table("KhachHang", self.khTable))
        self.h.clicked.connect(
            lambda: self.load_to_table("HoaDon", self.tableWidget))

    # Hàm xử lý hiển thị danh sách thú cưng
    def tcBtn_click(self):
        self.load_to_table(lambda: self.load_to_table("ThuCung", self.tcTable))

    # Hàm xử lý thêm dữ liệu vào database ở trang chính
    def add_both_to_database(self):
        # Lấy dữ liệu từ các trường nhập liệu
        cccd = self.cccdTxt.text()
        sdt = self.sdtTxt.text()
        ho_ten = self.hoTenTxt.text()
        email = self.emailTxt.text()
        loai_thu = self.loaiThuCB.currentText()
        dich_vu = self.dvCB.currentText()
        # Lấy đường dẫn hình ảnh
        url = cv.img_name
        # Giá cả tương ứng với các loại dịch vụ
        prices = {
            "Trông giữ thú cưng": 50000,
            "Chích ngừa": 100000,
            "Chải lông": 70000,
            "Khám định kỳ": 95000
        }

        # Thêm dữ liệu vào bảng KhachHang nếu mã cccd chưa tồn tại
        query = "INSERT IGNORE INTO KhachHang (cccd, sdt, hoten, email) VALUES (%s, %s, %s, %s)"
        values = (cccd, sdt, ho_ten, email)
        self.mycursor.execute(query, values)

        # Thêm thú cưng
        query = "INSERT INTO ThuCung (cccdKH, loai, dichvu, urlhinh) VALUES (%s, %s, %s, %s)"
        values = (cccd, loai_thu, dich_vu, url)
        self.mycursor.execute(query, values)

        # Lấy id thú cưng cuối cùng
        self.mycursor.execute(
            "SELECT idTC FROM ThuCung ORDER BY idTC DESC LIMIT 1")

        # Lấy ID cuối cùng
        result = self.mycursor.fetchone()
        last_id = int(result[0])
        print(last_id)

        # Lấy loại dịch vụ trong combobox
        dv = self.dvCB.currentText()

        print(dv)
        print(prices[dv])
        # Thêm hóa đơn
        query = "INSERT INTO HoaDon (cccdKH, idTC, thanhTien) VALUES (%s, %s, %s)"
        values = (cccd, last_id, prices[dv])
        self.mycursor.execute(query, values)
        # Cập nhật cơ sở dữ liệu
        self.mydb.commit()
        # Load lại bảng ThuCung
        self.load_to_table("ThuCung", self.tableWidget_2)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
